package org.example.app.usecase.impl;

import jakarta.transaction.Transactional;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import org.example.app.ports.out.DeviceHistoryRepositoryPort;
import org.example.app.ports.out.DeviceRepositoryPort;
import org.example.app.usecase.CreateDeviceUseCase;
import org.example.domain.Device;
import org.example.domain.enums.OperationTypeEnum;
import org.example.infra.rest.dto.CreateDeviceRequest;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
@RequiredArgsConstructor
public class CreateDeviceImpl implements CreateDeviceUseCase {

    private final DeviceRepositoryPort deviceRepositoryPort;
    private final DeviceHistoryRepositoryPort deviceHistoryRepositoryPort;

    @Transactional
    @Override
    public Device create(@NonNull CreateDeviceRequest request) {
        // Build domain entity (id is generated by persistence, creationTime is set by domain)
        Device newDevice = new Device(
                null,
                request.name(),
                normalizeBrand(request.brand()),
                request.state(),
                LocalDateTime.now(),
                null
        );

        Device savedDevice = deviceRepositoryPort.save(newDevice);
        deviceHistoryRepositoryPort.save(savedDevice, OperationTypeEnum.CREATION);
        return savedDevice;
    }

    private String normalizeBrand(String brand) {
        if (brand == null || brand.isEmpty()) {
            return brand;
        }
        return brand.toUpperCase();
    }
}
