package org.example.app.usecase.impl;

import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import org.example.app.ports.out.DeviceRepositoryPort;
import org.example.app.usecase.CreateDeviceUseCase;
import org.example.domain.Device;
import org.example.infra.rest.dto.CreateDeviceRequest;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
@RequiredArgsConstructor
public class CreateDeviceImpl implements CreateDeviceUseCase {

    private final DeviceRepositoryPort deviceRepositoryPort;

    @Override
    public Device create(@NonNull CreateDeviceRequest request) {
        // Build domain entity (id is generated by persistence, creationTime is set by domain)
        Device newDevice = new Device(
                null,
                request.name(),
                request.brand(),
                request.state(),
                LocalDateTime.now()
        );

        // Delegate persistence to the output port
        return deviceRepositoryPort.save(newDevice);
    }
}
